import type { ComponentType, SVGProps } from 'react';
import BeatStation from './nuuly-beats/beat-01-station';
import BeatSurface from './nuuly-beats/beat-02-surface';
import BeatHands from './nuuly-beats/beat-03-hands';

type NuulyBeat = 'station' | 'surface' | 'hands';

const FIGURES: Record<NuulyBeat, ComponentType<SVGProps<SVGSVGElement>>> = {
  station: BeatStation,
  surface: BeatSurface,
  hands: BeatHands,
};

/**
 * One Nuuly friction-beat figure. Same contract as FdteFigure: inline single-colour
 * art, `fill="currentColor"`, no box, flips with theme, .svg is the source of truth
 * (scripts/regen-nuuly-beats-tsx.mjs regenerates the .tsx — never hand-edit it).
 *
 * NO Nuuly-specific class. An earlier pass applied `.nuuly-beat-figure` as a "just in
 * case" hook mirroring `.fdte-figure`, then decided the fdte treatment did not apply —
 * and left the hook behind with no rule anywhere. check 9 caught it. `.oku-figure`
 * supplies everything these need: width, per-mode ink, and the `.friction-beat
 * .oku-figure { margin: 0 }` layout rule. If Paul's traced art later needs a Nuuly-only
 * adjustment, add the class AND its rule in the same commit.
 *
 * Specifically NOT `.fdte-figure`: that adds a 0.75px non-scaling stroke for FDT-E's
 * hairline-heavy filled paths, and globals.css marks it an FDT-E-scoped one-off.
 *
 * CURRENT ART IS PLACEHOLDER, regenerated by _placeholder-source.py in this folder.
 * Contour line drawings (stroke, currentColor) so they flip with theme for free —
 * Paul's requirement. All three show the SAME workstation: waist-height rolling
 * cart, monitor on an adjustable arm off one pole, garment rack off the other.
 * Keeping one cart across the set is what differentiates this from FDT-E's beats,
 * whose figures share a person type but no recurring object.
 *
 * The finished art will be traced from raster to filled outlines (house format is
 * fill-only, no stroke attribute) — visually identical, different technique.
 * Renders at a 300px cap in the beat's right column — see .friction-beat's
 * grid-template-columns in globals.css. Detail below ~40px of the 169px height
 * disappears; keep replacements to one figure and one oversized object.
 */
export function NuulyBeatFigure({ variant, alt }: { variant: NuulyBeat; alt: string }) {
  const Svg = FIGURES[variant];
  return (
    <figure className="oku-figure" role="img" aria-label={alt}>
      <Svg aria-hidden />
    </figure>
  );
}
